export default {
  id: "freebuff",
  priority: 45,
  hasFree: true,
  alias: "fb",
  uiAlias: "fb",
  display: {
    name: "Freebuff",
    icon: "bolt",
    color: "#10B981",
    textIcon: "FB",
  },
  category: "free",
  noAuth: true,
  transport: {
    baseUrl: "https://www.codebuff.com/api/v1/chat/completions",
    noAuth: true,
  },
  models: [
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4.1 Flash" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4.1 Flash", upstreamModelId: "deepseek/deepseek-v4-flash" },
    { id: "z-ai/glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash", upstreamModelId: "z-ai/glm-5.3-flash" },
    { id: "mimo/mimo-v2.6", name: "MiMo 2.6 Flash" },
    { id: "mimo-v2.6", name: "MiMo 2.6 Flash", upstreamModelId: "mimo/mimo-v2.6" },
    { id: "upstage/solar-pro4", name: "Solar Pro 4" },
    { id: "solar-pro4", name: "Solar Pro 4", upstreamModelId: "upstage/solar-pro4" },
    { id: "upstage/solar-mini4", name: "Solar Mini 4" },
    { id: "solar-mini4", name: "Solar Mini 4", upstreamModelId: "upstage/solar-mini4" },
    { id: "openai/gpt-6-luna", name: "GPT-6 Luna" },
    { id: "gpt-6-luna", name: "GPT-6 Luna", upstreamModelId: "openai/gpt-6-luna" },
    { id: "stealth/space-bunny-alpha", name: "Space Bunny Alpha" },
    { id: "fbc/ling-3.1-flash", name: "Ling 3.1 Flash" },
    { id: "fbc/laguna-s-2.1", name: "Laguna S 2.1" },
    { id: "claude-sonnet-5.5", name: "Claude Sonnet 5.5", upstreamModelId: "anthropic/claude-sonnet-5.5" },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", upstreamModelId: "google/gemini-3.8-flash" },
  ],
  passthroughModels: true,
};
